project:
  type: website
  preview:
    port: 3000

website:
  title: "Su Zhao"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/suzhc

format:
  html:
    theme: seem.scss
    highlight-style: seem.theme
    metadata:
      pagetitle: "{{< meta title >}}"
      freeze: true
      # Enable banner style title blocks
      title-block-banner: false
      # Can't yet enable this because it causes "On this page" to appear on index.html
      # even if I set its post-level `toc: false`
      # toc: true
      title-block-categories: false
      toc-depth: 5



