# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/suzhc.github.io',
                'doc_host': 'https://suzhc.github.io',
                'git_url': 'https://github.com/suzhc/suzhc.github.io',
                'lib_path': 'blog_tools'},
  'syms': {'blog_tools.core': {'blog_tools.core.create_ipynb': ('core.html#create_ipynb', 'blog_tools/core.py')}}}
