# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['create_ipynb']

# %% ../nbs/00_core.ipynb 3
import nbformat as nbf
from pathlib import Path


def create_ipynb(path: str):
    path = Path(path)
    path.mkdir(parents=True, exist_ok=True)
    
    nb = nbf.v4.new_notebook()
    nbf.write(nb, path / f'{path.name}.ipynb')
        

