# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['create_ipynb']

# %% ../nbs/00_core.ipynb 2
import nbformat as nbf
from fastcore.script import *
from pathlib import Path
from datetime import datetime


@call_parse
def create_ipynb(path: str, base_path: str = None):
    '''
    根据一个名称（例如：“my-first-blog”）,创建对应地 post 文件夹，以及对应的文件
    '''
    date = datetime.now().date().strftime("%Y-%m-%d")
    path = f'{date}-{path}'
    path = Path('nbs/blog/posts') / Path(path)
    if base_path:
        path = Path(base_path) / path
    path.mkdir(parents=True, exist_ok=True)
    
    nb = nbf.v4.new_notebook()
    nbf.write(nb, path / f'{path.name}.ipynb')
        

