project:
  type: website
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: 
        - custom.scss
        - yeti
    toc: true
    toc-depth: 4

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating

metadata-files: [nbdev.yml]